# Generated by Django 5.2.1 on 2026-02-24 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emotiontimeline',
            options={'ordering': ['date']},
        ),
        migrations.AlterUniqueTogether(
            name='emotiontimeline',
            unique_together={('user', 'date')},
        ),
        migrations.AddField(
            model_name='emotiontimeline',
            name='message_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emotiontimeline',
            name='negative_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emotiontimeline',
            name='neutral_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='emotiontimeline',
            name='positive_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='emotiontimeline',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_timeline', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sender', models.CharField(choices=[('USER', 'User'), ('BOT', 'Bot')], max_length=5)),
                ('emotion', models.CharField(blank=True, max_length=20, null=True)),
                ('emotion_score', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.RemoveField(
            model_name='emotiontimeline',
            name='average_score',
        ),
        migrations.RemoveField(
            model_name='emotiontimeline',
            name='dominant_emotion',
        ),
    ]
